package differenttypesofmethods;
//A method for some input in parameter and no returns and return type is void(void can't return any value)
public class InputMethod {
	public String name=null;
	public void getbill(int dosa1, double discount1 ) {
		System.out.println("Welcome to Taj hotel");
		name="Ranjith";
		double finalamount=dosa1-discount1;
		System.out.println("Your Bill amount has been: "+finalamount+"  bill generated by:  "+name);
		
	}
	public void getbill(int dosa, int discount ) {
		System.out.println("Welcome to GreenPark hotel");
		name="pallavi";
		int finalamount=dosa-discount;
		System.out.println("Your Bill amount has been: "+finalamount+"  bill generated by:  "+name);
		getbill(9, 4.3);
	}
	public void getbill(String BB, int amount ) {
		System.out.println("Welcome to RaMada hotel");
		//name="Pankaja";
		System.out.println("The BreakFast order Tha name has: "+BB+"  Amount has been: "+amount+"  bill generated by:  "+name);
		
	}

}
